### ISSUE TITLE
Problem :: Bearer Token expected ...

### ISSUE THREAD

**Issue by PreinfalkG** [Wolbolar/IPSymconTahoma#2]
Hallo Wolbolar

Vorerst DANKE für dein TaHoma Modul. Ich habe das Modul seit letzter Woche im Einsatz!

Aber jetzt bekomme ich mehr oder weniger Überall den Fehler 'Bearer Token expected'. Und zwar regelmäßig im LogFile mit Absender 'TimerPool', bei der Splitter Instanz und bei jedem TaHoma Device. Klar, der 'Bearer Token' ist ein grundlegende Basis für die TaHoma API und somit von deinem Modul.

Uncool ist jetzt aber, dass ich die einzelnen IPS Ansichten (Konfigurationsform, Device) nicht mehr Einsehen / Bearbeiten kann  -> siehe Screenshot 1 & 2

FRAGE: Hast du dazu eine Idee oder Lösung?

**Screenshot 1**
![01-Bearer Token expected](https://user-images.githubusercontent.com/16906959/148631482-f533cffb-9f15-4c3b-85ed-c60780fe6f26.jpg)

**Screenshot 2**
![02-Bearer Token expected](https://user-images.githubusercontent.com/16906959/148631484-56267aa9-33cb-46ad-879d-38ff27d46a7c.jpg)

**Beim öffnen einer TaHoma Device Instanz kommt diese Fehlermeldung
----------------------------------------------------------------------------------**

`Konnte Konfigurationsform nicht laden
Warning: Bearer Token expected in C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php on line 141

Fatal error: Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php:142
Stack trace:
#0 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(142): json_decode(false, true)
#1 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(498): TaHomaDevice->RequestStatus()
#2 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(457): TaHomaDevice->CheckRequest()
#3 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(444): TaHomaDevice->FormHead()
#4 C:\Windows\System32\-(3): TaHomaDevice->GetConfigurationForm()
#5 {main}
  thrown in C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php on line 142
Abort Processing during Fatal-Error: Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php:142
Stack trace:
#0 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(142): json_decode(false, true)
#1 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(498): TaHomaDevice->RequestStatus()
#2 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(457): TaHomaDevice->CheckRequest()
#3 C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php(444): TaHomaDevice->FormHead()
#4 C:\Windows\System32\-(3): TaHomaDevice->GetConfigurationForm()
#5 {main}
  thrown {via function '!IPS_PhpFatalErrorHandler!'} 
..:: Details ::..
Error in Script 'C:\ProgramData\Symcon\modules\.store\fonzo.ipsymcontahoma\TaHomaDevice\module.php' on Line 142 (Code: -32603)`

**Comment by DinoBordonaro** [comment]
Hallo,
das Problem hab ich jetzt auch, obwohl es Monate einwandfrei lief.

Gibts hier ne Lösung?
